# -*- coding: utf-8 -*-
"""ix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/157GAgjARRzPnKvPE_1dwa6i3uVnl7MJV
"""

# 균등 분포, 정규 분포, 이항 분포 - 베르누이 분포



# alco = pd.read_csv("niaaa-report.csv", index_col=["State", "Year"])
# multi = pd.MultiIndex.from_tuples(( ... ))

alco.index = multi

beer_seriesNY = alco.ix['New York']['Beer']
beer_seriesCA = alco.ix['California']['Beer']

beer_seriesNY.corr(beer_seriesCA)

beer_seriesCA.cov(beer_seriesNY)

[x.skew() for x in (beer_seriesCA, beer_seriesNY)]

frameNY = alco.ix['New York']
frameNY.skew()

frameNY.corr()

frameNY.cov()

pop = pd.read_csv(“population2000-2009.csv”, index_col=”State”)

pop_seriesNY = pop.ix["New York"][:-2]
pop_seriesNY.index

pop_seriesNY.index = pop_seriesNY.index.map(int)

frameNY.ix[range(2000:2009)].corrwith(pop_seriesNY)


from scipy.stats import pearsonr

pop_sorted = pop_seriesNY.sort_index()
alco_10 = alco.ix['New York'][-10:]

corrs = [(bev,) + pearsonr(alco_10[bev], pop_sorted) for bev in alco_10.columns]

pd.DataFrame(corrs, columns=("bev", "r", "p-value")).set_index("bev")

alco2009.corr()

pearsonr(alco2009["Wine"], alco2009["Beer"])



