# -*- coding: utf-8 -*-
"""viii.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qkUXY2caej7ksgVRTEJxgglB37WRtYcB
"""

import matplotlib, matplotlib.pyplot as plt
import pickle, pandas as pd

alco = pickle.load(open("alco.pickle", "rb"))
del alco["Total"]
columns, years = alco.unstack().columns.levels

states = pd.read_csv("states.csv", index_col="State")

frames = [pd.merge(alco[column].unstack(), states,
                   left_index=True, right_index=True).sort_values(2009)
          for column in columns]

span = max(years) - min(years) + 1


matplotlib.style.use("ggplot")


STEP = 5
for pos, (draw, style, column, frame) in enumerate(zip(
        (plt.contourf, plt.contour, plt.imshow), # (1)
        (plt.cm.autumn, plt.cm.cool, plt.cm.spring),
        columns, frames)):

    plt.subplot(2, 2, pos + 1)

    draw(frame[frame.columns[:span]], cmap=style, aspect="auto")

    plt.colorbar()
    plt.title(column)
    plt.xlabel("Year")
    plt.xticks(range(0, span, STEP), frame.columns[:span:STEP])
    plt.yticks(range(0, frame.shape[0], STEP), frame.Postal[::STEP])
    plt.xticks(rotation=-17)


plt.tight_layout()
plt.savefig("pyplot-all.pdf")
plt.show()

# clf() : 초기화



import matplotlib, matplotlib.pyplot as plt
import pickle, pandas as pd

alco = pickle.load(open("alco.pickle", "rb"))

BEVERAGE = "Beer"
years = alco.index.levels[1]
states = ("New Hampshire", "Colorado", "Utah")

plt.xkcd()
matplotlib.style.use("ggplot")

for state in states:
    ydata = alco.ix[state][BEVERAGE]
    plt.plot(years, ydata, "-o")
    plt.annotate(s="Peak", xy=(ydata.argmax(), ydata.max()),
                 xytext=(ydata.argmax() + 0.5, ydata.max() + 0.1),
                 arrowprops={"facecolor": "black", "shrink": 0.2})

plt.ylabel(BEVERAGE + " consumption")
plt.title("And now in xkcd...")
plt.legend(states)

plt.savefig("pyplot-legend-xkcd.pdf")



from pandas.tools.plotting import scatter_matrix
import matplotlib, matplotlib.pyplot as plt
import pickle, pandas as pd

alco = pickle.load(open("alco.pickle", "rb"))

matplotlib.style.use("ggplot")

STATE = "New Hampshire"
statedata = alco.ix[STATE].reset_index()
statedata.plot.scatter("Beer", "Wine", c="Year", s=100, cmap=plt.cm.autumn)

plt.title("%s: From Beer to Wine in 32 Years" % STATE)
plt.savefig("scatter-plot.pdf")

