# -*- coding: utf-8 -*-
"""Ⅱ..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dfTFaLiTUVDEXuS4SJyp_yBpPGn3ru_D
"""

"Hello, world! \t\t\n".strip()

"Hello, world!".split()

"Hello, world!".split(" ")

"www.networksciencelab.com".split(".")

", ".join(["alpha", "bravo", "charlie", "delta"])

"-".join("1.617.305.1985".split("."))

" ".join("This string\n\r has many\t\tspaces".split())

"www.networksciencelab.com".find(".com")

"www.networksciencelab.com".count(".")

seq = ["alpha", "bravo", "charlie", "delta"]
dict(enumerate(seq))

kseq = "abcd"
vseq = ["alpha", "bravo", "charlie", "delta"]
dict(zip(kseq, vseq))



# x for x in myList

# x for x in myList if x >= 0

# x**2 for x in myList

# 1/x for x in myList

# line for line in [l.strip() for l in infinile] if line



from collections import Counter
phrase = "a man a plan a canal panama"
cntr = Counter(phrase.split())
cntr
cntr.most_common()

cntrDict = dict(cntr.most_common())
cntrDict

cntrDict['a']



import urllib.parse

try:
    with urllib.request.urlopen("http://networksciencelab.com") as doc:
        html = doc.read()
except:
    print("could not open %s" %doc, file=sys.err)

import urllib.parse
URL = "http://networksciencelab.com/index.html;param?foo=bar#content"
urllib.parse.urlparse(URL)



# compiledPattern = re.compile(pattern, flags = 0)

imoprt re

re.split(r"W", " Hello, world!")

mo = re.match(r"\d+", "067 Starts with a number")

mo

mo.group()

print(re.match(r"\d+", "Does not start with a number"))

re.search(r"[a-z]+", "0010010 Has at least one 010 letter 0010010", re.I)

re.search(r"[a-z]+", "0010010 Has at least one 010 letter 0010010")

re.findall(r"[a-z]+", "0010010 Has at least one 010 letter 0010010", re.I)

re.sub(r"[a-z ]+", "[...]", "0010010 has at least one 010 letter 0010010")



import glob
glob.glob("*.txt")



with open ("myData.pickle", "wb") as oFile:
  pickle.dump(object, oFile)

with open ("myData.pickle", "rb") as iFile:
 object = picle.load(iFile)